version: '3'

services:
  client:
    build:
      context: ../
      dockerfile: ./packages/client/Dockerfile
    container_name: client
    ports:
      - "11900:11900"
    volumes:
      - type: volume
        source: client_volume
        target: /app
    env_file: ../env/client/.env

  database:
    container_name: postgres
    build:
      context: ../
      dockerfile: ./packages/server/database.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}

  server:
    build:
      context: ../
      dockerfile: ./packages/server/Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: server_volume
        target: /app
    env_file: ../env/server/.env
    depends_on:
      - database

volumes:
  client_volume:
    name: client_volume
    driver: local
    driver_opts:
      # todo: docker compose doesn't support relative path in device, need to wait next release
      # not working in windows powershell
      device: ${PWD}/packages/client/app
      type: none
      o: bind

  server_volume:
    name: server_volume
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/packages/server
      o: bind
